### ISSUE TITLE
Support for mermaid

### ISSUE THREAD

**Issue by dveeden** [pingcap/docs#15560]
> @qiancai we can't use [mermaid](https://github.com/mermaid-js/mermaid) for docs like [on github](https://github.blog/2022-02-14-include-diagrams-markdown-files-mermaid/), right?

We can't, because the current tool for generating PDFs from docs doesn't support Mermaid.

_Originally posted by @Yuiham in https://github.com/pingcap/docs/issues/5783#issuecomment-1831325879_

**Comment by dveeden** [comment]
Possible options:
- https://github.com/raghur/mermaid-filter
- https://github.com/timofurrer/pandoc-mermaid-filter

**Comment by Oreoxmt** [comment]
@dveeden Mermaid is now supported on the docs website! 🎉

The documentation site now supports Mermaid diagram via this PR https://github.com/pingcap/website-docs/pull/685. You can now use standard ` ```mermaid ` code blocks in Markdown files and diagrams will render automatically.

As a first step, I've converted the 2PC in TiDB sequence diagram from a PNG image to Mermaid code in https://github.com/pingcap/docs/pull/22560.

Regarding PDF rendering support for Mermaid diagrams, I'll work on that separately as a follow-up.

**Comment by dveeden** [comment]
@Oreoxmt Nice!

I noticed in that PR that you didn't remove the image that the diagram replaced?

**Comment by Oreoxmt** [comment]
@dveeden Thanks for flagging this! The original image wasn't removed because it's still referenced by archived versions of the docs, such as https://docs-archive.pingcap.com/tidb/v8.4/optimistic-transaction/.

If we delete it now, those older pages would break with a 404, since all versions currently share the same image assets rather than maintaining them per version.

This is actually a nice benefit of Mermaid, the diagrams live right in the Markdown source and get version-controlled along with the content, so updating or removing them for a specific version is much safer.

**Comment by kennytm** [comment]
Since this issue is not closed, maybe let's also use this as a tracking issue for the convertible diagrams. (Collected by GPT-5.4-Mini, so may contain many false-positives.)

----

- [ ] [best-practices/high-concurrency-best-practices.md](https://github.com/pingcap/docs/blob/90ac5d974e054305fa18ca38dcf1ee77f0123b02/best-practices/high-concurrency-best-practices.md) line `40`: `tidb-data-overview.png`
- [ ] [best-practices/high-concurrency-best-practices.md](https://github.com/pingcap/docs/blob/90ac5d974e054305fa18ca38dcf1ee77f0123b02/best-practices/high-concurrency-best-practices.md) lines `121`, `153`: `tikv-Region-split.png`, `table-Region-range.png`
- [ ] [best-practices/massive-regions-best-practices.md](https://github.com/pingcap/docs/blob/90ac5d974e054305fa18ca38dcf1ee77f0123b02/best-practices/massive-regions-best-practices.md) line `17`: `raft-process.png`
- [ ] [br/br-log-architecture.md](https://github.com/pingcap/docs/blob/90ac5d974e054305fa18ca38dcf1ee77f0123b02/br/br-log-architecture.md) lines `14`: `br-log-arch.png`
- [x] [br/br-log-architecture.md](https://github.com/pingcap/docs/blob/90ac5d974e054305fa18ca38dcf1ee77f0123b02/br/br-log-architecture.md) lines `20`, `60`: `br-log-arch.png`, `br-log-backup-ts.png`, `pitr-ts.png` #22708
- [ ] [br/br-snapshot-architecture.md](https://github.com/pingcap/docs/blob/90ac5d974e054305fa18ca38dcf1ee77f0123b02/br/br-snapshot-architecture.md) lines `14`: `br-snapshot-arch.png`
- [x] [br/br-snapshot-architecture.md](https://github.com/pingcap/docs/blob/90ac5d974e054305fa18ca38dcf1ee77f0123b02/br/br-snapshot-architecture.md) lines `20`, `57`: `br-snapshot-backup-ts.png`, `br-snapshot-restore-ts.png` #22708
- [ ] [develop/dev-guide-proxysql-integration.md](https://github.com/pingcap/docs/blob/90ac5d974e054305fa18ca38dcf1ee77f0123b02/develop/dev-guide-proxysql-integration.md) line `33`: `proxysql-client-side-tidb-cloud.png`
- [ ] [dm/dm-arch.md](https://github.com/pingcap/docs/blob/90ac5d974e054305fa18ca38dcf1ee77f0123b02/dm/dm-arch.md) line `12`: `dm-architecture-2.0.png`
- [ ] [dm/dm-continuous-data-validation.md](https://github.com/pingcap/docs/blob/90ac5d974e054305fa18ca38dcf1ee77f0123b02/dm/dm-continuous-data-validation.md) lines `276`, `280`: `dm-validator-summary.jpeg`, `dm-validator-lifecycle.jpeg`
- [ ] [dm/dm-replication-logic.md](https://github.com/pingcap/docs/blob/90ac5d974e054305fa18ca38dcf1ee77f0123b02/dm/dm-replication-logic.md) line `30`: `dm-dml-replication-logic.png`
- [ ] [dm/feature-shard-merge-optimistic.md](https://github.com/pingcap/docs/blob/90ac5d974e054305fa18ca38dcf1ee77f0123b02/dm/feature-shard-merge-optimistic.md) line `110`: `optimistic-ddl-flow.png`
- [x] [dm/feature-shard-merge-pessimistic.md](https://github.com/pingcap/docs/blob/90ac5d974e054305fa18ca38dcf1ee77f0123b02/dm/feature-shard-merge-pessimistic.md) line `60`: `shard-ddl-flow.png` #22708
- [ ] [dr-backup-restore.md](https://github.com/pingcap/docs/blob/90ac5d974e054305fa18ca38dcf1ee77f0123b02/dr-backup-restore.md) line `19`: `dr-backup-and-restore.png`
- [ ] [dr-solution-introduction.md](https://github.com/pingcap/docs/blob/90ac5d974e054305fa18ca38dcf1ee77f0123b02/dr-solution-introduction.md) lines `33`, `45`, `56`, `64`, `72`, `82`, `92`: `tidb-architecture.png`, `cdc-architecture.png`, `br-snapshot-arch.png`, `ticdc-dr.png`, `multi-replica-dr.png`, `ticdc-multi-replica-dr.png`, `br-dr.png`
- [ ] [multi-data-centers-in-one-city-deployment.md](https://github.com/pingcap/docs/blob/90ac5d974e054305fa18ca38dcf1ee77f0123b02/multi-data-centers-in-one-city-deployment.md) lines `45`, `53`, `67`: `deploy-3dc.png`, `deploy-3dc-dr.png`, `deploy-3dc-optimize.png`
- [x] [pessimistic-transaction.md](https://github.com/pingcap/docs/blob/90ac5d974e054305fa18ca38dcf1ee77f0123b02/pessimistic-transaction.md) lines `150`, `158`, `174`: `pessimistic-transaction-commit.png`, `pessimistic-transaction-in-tidb.png`, `pessimistic-transaction-pipelining.png` #22708
- [ ] [sql-optimization-concepts.md](https://github.com/pingcap/docs/blob/90ac5d974e054305fa18ca38dcf1ee77f0123b02/sql-optimization-concepts.md) line `11`: `sql-optimization.png`
- [ ] [sql-tuning-best-practice.md](https://github.com/pingcap/docs/blob/90ac5d974e054305fa18ca38dcf1ee77f0123b02/sql-tuning-best-practice.md) line `470`: `execution-plan-traverse.png`
- [ ] [sql-tuning-best-practice.md](https://github.com/pingcap/docs/blob/90ac5d974e054305fa18ca38dcf1ee77f0123b02/sql-tuning-best-practice.md) lines `159`, `470`: `workflow-tiflash.png`, `execution-plan-traverse.png`
- [ ] [three-data-centers-in-two-cities-deployment.md](https://github.com/pingcap/docs/blob/90ac5d974e054305fa18ca38dcf1ee77f0123b02/three-data-centers-in-two-cities-deployment.md) lines `31`, `51`: `three-data-centers-in-two-cities-deployment-01.png`, `three-data-centers-in-two-cities-deployment-02.png`
- [ ] [ticdc/ticdc-architecture.md](https://github.com/pingcap/docs/blob/90ac5d974e054305fa18ca38dcf1ee77f0123b02/ticdc/ticdc-architecture.md) lines `19`, `44`: `ticdc-new-arch-1.png`, `ticdc-new-arch-2.png`
- [ ] [ticdc/ticdc-bidirectional-replication.md](https://github.com/pingcap/docs/blob/90ac5d974e054305fa18ca38dcf1ee77f0123b02/ticdc/ticdc-bidirectional-replication.md) line `20`: `ticdc-bidirectional-replication.png`
- [ ] [ticdc/ticdc-changefeed-overview.md](https://github.com/pingcap/docs/blob/90ac5d974e054305fa18ca38dcf1ee77f0123b02/ticdc/ticdc-changefeed-overview.md) line `14`: `ticdc-changefeed-state-transfer.png`
- [ ] [ticdc/ticdc-classic-architecture.md](https://github.com/pingcap/docs/blob/90ac5d974e054305fa18ca38dcf1ee77f0123b02/ticdc/ticdc-classic-architecture.md) lines `19`, `29`, `40`, `73`, `79`: `ticdc-architecture-1.jpg`, `ticdc-architecture-2.jpg`, `ticdc-architecture-3.PNG`, `ticdc-architecture-6.jpg`, `ticdc-architecture-5.jpg`
- [ ] [ticdc/ticdc-overview.md](https://github.com/pingcap/docs/blob/90ac5d974e054305fa18ca38dcf1ee77f0123b02/ticdc/ticdc-overview.md) line `66`: `cdc-architecture.png`
- [ ] [ticdc/ticdc-storage-consumer-dev-guide.md](https://github.com/pingcap/docs/blob/90ac5d974e054305fa18ca38dcf1ee77f0123b02/ticdc/ticdc-storage-consumer-dev-guide.md) line `22`: `ticdc-storage-consumer-overview.png`
- [ ] [tidb-architecture.md](https://github.com/pingcap/docs/blob/90ac5d974e054305fa18ca38dcf1ee77f0123b02/tidb-architecture.md) line `30`: `tidb-architecture-v6.png`
- [ ] [tidb-cloud/architecture-concepts.md](https://github.com/pingcap/docs/blob/90ac5d974e054305fa18ca38dcf1ee77f0123b02/tidb-cloud/architecture-concepts.md) line `71`: `tidb-cloud-dedicated-architecture.png`
- [ ] [tidb-cloud/integrate-tidbcloud-with-aws-lambda.md](https://github.com/pingcap/docs/blob/90ac5d974e054305fa18ca38dcf1ee77f0123b02/tidb-cloud/integrate-tidbcloud-with-aws-lambda.md) line `27`: `aws-lambda-structure-overview.png`
- [ ] [tidb-cloud/integrate-tidbcloud-with-n8n.md](https://github.com/pingcap/docs/blob/90ac5d974e054305fa18ca38dcf1ee77f0123b02/tidb-cloud/integrate-tidbcloud-with-n8n.md) line `81`: `integration-n8n-workflow-rss.jpg`
- [ ] [tidb-cloud/recovery-group-overview.md](https://github.com/pingcap/docs/blob/90ac5d974e054305fa18ca38dcf1ee77f0123b02/tidb-cloud/recovery-group-overview.md) line `14`: `recovery-group-overview.png`
- [ ] [tidb-cloud/set-up-private-endpoint-connections-on-azure.md](https://github.com/pingcap/docs/blob/90ac5d974e054305fa18ca38dcf1ee77f0123b02/tidb-cloud/set-up-private-endpoint-connections-on-azure.md) line `38`: `azure-private-endpoint-arch.png`
- [ ] [tidb-cloud/set-up-private-endpoint-connections-on-google-cloud.md](https://github.com/pingcap/docs/blob/90ac5d974e054305fa18ca38dcf1ee77f0123b02/tidb-cloud/set-up-private-endpoint-connections-on-google-cloud.md) line `38`: `google-cloud-psc-endpoint-overview.png`
- [ ] [tidb-cloud/set-up-private-endpoint-connections-serverless.md](https://github.com/pingcap/docs/blob/90ac5d974e054305fa18ca38dcf1ee77f0123b02/tidb-cloud/set-up-private-endpoint-connections-serverless.md) line `22`: `aws-private-endpoint-arch.png`
- [ ] [tidb-cloud/set-up-private-endpoint-connections.md](https://github.com/pingcap/docs/blob/90ac5d974e054305fa18ca38dcf1ee77f0123b02/tidb-cloud/set-up-private-endpoint-connections.md) line `22`: `aws-private-endpoint-arch.png`
- [ ] [tidb-cloud/tidb-cloud-intro.md](https://github.com/pingcap/docs/blob/90ac5d974e054305fa18ca38dcf1ee77f0123b02/tidb-cloud/tidb-cloud-intro.md) line `11`: `tidb-cloud-overview.png`
- [ ] [tidb-cloud/tidb-cloud-intro.md](https://github.com/pingcap/docs/blob/90ac5d974e054305fa18ca38dcf1ee77f0123b02/tidb-cloud/tidb-cloud-intro.md) line `123`: `tidb-cloud-architecture.png`
- [ ] [tidb-cloud/tidb-node-group-overview.md](https://github.com/pingcap/docs/blob/90ac5d974e054305fa18ca38dcf1ee77f0123b02/tidb-cloud/tidb-node-group-overview.md) line `24`: `implementation-of-tidb-node-group.png`
- [ ] [tidb-cloud/tidb-x-architecture.md](https://github.com/pingcap/docs/blob/90ac5d974e054305fa18ca38dcf1ee77f0123b02/tidb-cloud/tidb-x-architecture.md) lines `76`, `100`, `140`: `tidb-x-architecture.png`, `tidb-classic-vs-tidb-x-1.png`, `tidb-classic-vs-tidb-x-2.png`
- [ ] [tidb-cloud/tiproxy-management.md](https://github.com/pingcap/docs/blob/90ac5d974e054305fa18ca38dcf1ee77f0123b02/tidb-cloud/tiproxy-management.md) line `84`: `tiproxy-topology.png`
- [ ] [tidb-computing.md](https://github.com/pingcap/docs/blob/90ac5d974e054305fa18ca38dcf1ee77f0123b02/tidb-computing.md) lines `135`, `149`, `155`: `tidb-computing-native-sql-flow.jpeg`, `tidb-computing-dist-sql-flow.png`, `tidb-computing-tidb-sql-layer.png`
- [ ] [tidb-lightning/tidb-lightning-faq.md](https://github.com/pingcap/docs/blob/90ac5d974e054305fa18ca38dcf1ee77f0123b02/tidb-lightning/tidb-lightning-faq.md) line `151`: `lightning-faq-source-cluster-topology.jpg`
- [ ] [tidb-lightning/tidb-lightning-faq.md](https://github.com/pingcap/docs/blob/90ac5d974e054305fa18ca38dcf1ee77f0123b02/tidb-lightning/tidb-lightning-faq.md) lines `161`, `165`: `lightning-faq-situation-1.jpg`, `lightning-faq-situation-2.jpg`
- [ ] [tidb-lightning/tidb-lightning-overview.md](https://github.com/pingcap/docs/blob/90ac5d974e054305fa18ca38dcf1ee77f0123b02/tidb-lightning/tidb-lightning-overview.md) line `29`: `tidb-lightning-architecture.png`
- [ ] [tidb-scheduling.md](https://github.com/pingcap/docs/blob/90ac5d974e054305fa18ca38dcf1ee77f0123b02/tidb-scheduling.md) line `88`: `tikv-store-status-relationship.png`
- [ ] [tidb-storage.md](https://github.com/pingcap/docs/blob/90ac5d974e054305fa18ca38dcf1ee77f0123b02/tidb-storage.md) lines `10`, `41`, `54`, `71`: `tidb-storage-architecture-1.png`, `tidb-storage-1.png`, `tidb-storage-2.png`, `tidb-storage-3.png`
- [ ] [tiflash-performance-tuning-methods.md](https://github.com/pingcap/docs/blob/90ac5d974e054305fa18ca38dcf1ee77f0123b02/tiflash-performance-tuning-methods.md) lines `107`, `113`: `ch-2tiflash-raft-io-flow.png`, `ch-1tiflash-raft-io-flow-cloud.png`
- [ ] [tiflash/tiflash-overview.md](https://github.com/pingcap/docs/blob/90ac5d974e054305fa18ca38dcf1ee77f0123b02/tiflash/tiflash-overview.md) line `21`: `tidb-storage-architecture-1.png`
- [ ] [tiflash/tiflash-pipeline-model.md](https://github.com/pingcap/docs/blob/90ac5d974e054305fa18ca38dcf1ee77f0123b02/tiflash/tiflash-pipeline-model.md) line `33`: `tiflash-pipeline-model.png`
- [ ] [two-data-centers-in-one-city-deployment.md](https://github.com/pingcap/docs/blob/90ac5d974e054305fa18ca38dcf1ee77f0123b02/two-data-centers-in-one-city-deployment.md) line `28`: `two-dc-replication-1.png`
