### ISSUE TITLE
Use EBNF instead of images to render sqlgrams

### ISSUE THREAD

**Issue by kennytm** [pingcap/docs#4389]
## Change Request

Please answer the following questions before submitting your issue. Thanks!

1. Describe what you find is inappropriate or missing in the existing docs.

Recently we support rendering EBNF code directly as SVG (sample: https://docs.pingcap.com/tidb/stable/sql-statement-backup), and thus no longer needs to use PNG images for the sqlgrams (see #4342 for details). We should upgrade the remaining docs to use the new feature.

2. Describe your suggestion or addition.

Change the following pages to use ` ```ebnf+diagram `:

- [x] basic-sql-operations.md
- [x] expression-syntax.md (pingcap/docs-cn#5324)
- [x] #17465
- [x] mysql-compatibility.md
- [x] sql-statements/sql-statement-add-column.md (pingcap/docs-cn#5324)
- [x] sql-statements/sql-statement-add-index.md (pingcap/docs-cn#5324)
- [x] sql-statements/sql-statement-admin-cancel-ddl.md (pingcap/docs-cn#5324)
- [x] sql-statements/sql-statement-admin-check-table-index.md (pingcap/docs-cn#5324)
- [x] sql-statements/sql-statement-admin-checksum-table.md (pingcap/docs-cn#5324)
- [x] sql-statements/sql-statement-admin-show-ddl.md (pingcap/docs-cn#5324)
- [x] sql-statements/sql-statement-admin.md (pingcap/docs-cn#5324)
- [x] sql-statements/sql-statement-alter-database.md (pingcap/docs-cn#5324)
- [x] sql-statements/sql-statement-alter-index.md (pingcap/docs-cn#5324)
- [x] sql-statements/sql-statement-alter-instance.md (pingcap/docs-cn#5324)
- [x] sql-statements/sql-statement-alter-table.md (pingcap/docs-cn#5324)
- [x] sql-statements/sql-statement-alter-user.md (pingcap/docs-cn#5324)
- [x] sql-statements/sql-statement-analyze-table.md (pingcap/docs-cn#5324)
- [x] sql-statements/sql-statement-backup.md (#4342)
- [x] sql-statements/sql-statement-begin.md (pingcap/docs-cn#5376)
- [x] sql-statements/sql-statement-change-column.md (pingcap/docs-cn#5376)
- [x] sql-statements/sql-statement-commit.md (pingcap/docs-cn#5376)
- [x] sql-statements/sql-statement-create-binding.md (pingcap/docs-cn#5376)
- [x] sql-statements/sql-statement-create-database.md (pingcap/docs-cn#5376)
- [x] sql-statements/sql-statement-create-index.md (pingcap/docs-cn#5376)
- [x] sql-statements/sql-statement-create-role.md (pingcap/docs-cn#5376)
- [x] sql-statements/sql-statement-create-sequence.md (pingcap/docs-cn#5376)
- [x] sql-statements/sql-statement-create-table-like.md (pingcap/docs-cn#5376)
- [x] sql-statements/sql-statement-create-table.md (pingcap/docs-cn#5376)
- [x] sql-statements/sql-statement-create-user.md (pingcap/docs-cn#5376)
- [x] sql-statements/sql-statement-create-view.md (pingcap/docs-cn#5376)
- [x] sql-statements/sql-statement-deallocate.md (pingcap/docs-cn#5376)
- [x] sql-statements/sql-statement-delete.md (pingcap/docs-cn#5376)
- [x] sql-statements/sql-statement-do.md (pingcap/docs-cn#5376)
- [x] sql-statements/sql-statement-drop-binding.md (pingcap/docs-cn#5376)
- [x] sql-statements/sql-statement-drop-column.md (pingcap/docs-cn#5376)
- [x] sql-statements/sql-statement-drop-database.md (pingcap/docs-cn#5376)
- [x] sql-statements/sql-statement-drop-index.md (pingcap/docs-cn#5376)
- [x] sql-statements/sql-statement-drop-role.md (pingcap/docs-cn#5376)
- [x] sql-statements/sql-statement-drop-sequence.md (pingcap/docs-cn#5376)
- [x] sql-statements/sql-statement-drop-stats.md (pingcap/docs-cn#5376)
- [x] sql-statements/sql-statement-drop-table.md (pingcap/docs-cn#5376)
- [x] sql-statements/sql-statement-drop-user.md (pingcap/docs-cn#5376)
- [x] sql-statements/sql-statement-drop-view.md (pingcap/docs-cn#5376)
- [x] sql-statements/sql-statement-execute.md (https://github.com/pingcap/docs-cn/pull/5540)
- [x] sql-statements/sql-statement-explain-analyze.md (https://github.com/pingcap/docs-cn/pull/5540)
- [x] sql-statements/sql-statement-explain.md (https://github.com/pingcap/docs-cn/pull/5540)
- [x] sql-statements/sql-statement-flashback-table.md (https://github.com/pingcap/docs-cn/pull/5540)
- [x] sql-statements/sql-statement-flush-privileges.md (https://github.com/pingcap/docs-cn/pull/5540)
- [x] sql-statements/sql-statement-flush-status.md (https://github.com/pingcap/docs-cn/pull/5540)
- [x] sql-statements/sql-statement-flush-tables.md (https://github.com/pingcap/docs-cn/pull/5540)
- [x] sql-statements/sql-statement-grant-privileges.md (https://github.com/pingcap/docs-cn/pull/5540)
- [x] sql-statements/sql-statement-grant-role.md (https://github.com/pingcap/docs-cn/pull/5540)
- [x] sql-statements/sql-statement-insert.md (https://github.com/pingcap/docs-cn/pull/5540)
- [x] sql-statements/sql-statement-kill.md (https://github.com/pingcap/docs-cn/pull/5540)
- [x] sql-statements/sql-statement-load-data.md (https://github.com/pingcap/docs-cn/pull/5540)
- [x] sql-statements/sql-statement-load-stats.md (https://github.com/pingcap/docs-cn/pull/5540)
- [x] sql-statements/sql-statement-modify-column.md (https://github.com/pingcap/docs-cn/pull/5540)
- [x] sql-statements/sql-statement-prepare.md (https://github.com/pingcap/docs-cn/pull/5540)
- [x] sql-statements/sql-statement-recover-table.md (https://github.com/pingcap/docs-cn/pull/5540)
- [x] sql-statements/sql-statement-rename-index.md (https://github.com/pingcap/docs-cn/pull/5540)
- [x] sql-statements/sql-statement-rename-table.md (https://github.com/pingcap/docs-cn/pull/5540)
- [x] sql-statements/sql-statement-replace.md (https://github.com/pingcap/docs-cn/pull/5540)
- [x] sql-statements/sql-statement-restore.md (#4342)
- [x] sql-statements/sql-statement-revoke-privileges.md (https://github.com/pingcap/docs-cn/pull/5540)
- [x] sql-statements/sql-statement-revoke-role.md (https://github.com/pingcap/docs-cn/pull/5540)
- [x] sql-statements/sql-statement-rollback.md (https://github.com/pingcap/docs-cn/pull/5540)
- [x] #17274
- [x] #17042
- [x] #17090
- [x] #17001
- [x] #17044
- [x] sql-statements/sql-statement-set-transaction.md
- [x] #17046
- [x] sql-statements/sql-statement-show-analyze-status.md
- [x] sql-statements/sql-statement-show-backups.md (#4342)
- [x] #17032
- [x] #17008
- [x] #17034
- [x] #17017
- [x] #17086
- [x] #17024
- [x] #17048
- [x] #17088
- [x] #17073
- [x] #17030
- [x] #17005
- [x] #17010
- [x] #17080
- [x] #17050
- [x] #17084
- [x] #17003
- [x] #17026
- [x] #17022
- [x] #17069
- [x] #17071
- [x] #17019
- [x] sql-statements/sql-statement-show-status.md https://github.com/pingcap/docs/pull/15363
- [x] #17092
- [x] #17094
- [x] #17064
- [x] #17067
- [x] #16999
- [x] #16997
- [x] #16993
- [x] #17096
- [x] sql-statements/sql-statement-start-transaction.md
- [x] #16995
- [x] sql-statements/sql-statement-truncate.md https://github.com/pingcap/docs/pull/16050
- [x] #17098
- [x] sql-statements/sql-statement-use.md #16049
- [x] #17463
- [x] #17467

3. Provide some reference materials (documents, websites, etc) if you could.

You can use https://kennytm.github.io/website-docs/dist/ to preview the rendered result.

Supported grammar:

```
Grammar     ::= Production+
Production  ::= NonTerminal "::=" Choice
Choice      ::= Seq ('|' Seq)*
Seq         ::= Item+
Item        ::= Primary ('*' | '+' | '?')?
Primary     ::= Terminal | NonTerminal | '(' Choice ')'
Terminal    ::= '"' '[^"]'* '"' | "'" "[^']"* "'"
NonTerminal ::= '[0-9a-zA-Z_]'+
```

**Comment by kennytm** [comment]
🤔 I just realized when `(x y z)*` rendered the nodes will be traveled in opposite order.

![2-fs8](https://user-images.githubusercontent.com/103023/105017827-36b35180-5a7f-11eb-8f83-a57ce023d214.png)

But the old image, which flips the nodes, does not look good at all.

![1-fs8](https://user-images.githubusercontent.com/103023/105017829-37e47e80-5a7f-11eb-8f4f-7f9f88609c28.png)

We could fix this by drawing it like `((x y z)+)?` ([CockroachDB's style](https://www.cockroachlabs.com/docs/stable/sql-grammar.html#like_table_option_list)):

![1-fs8](https://user-images.githubusercontent.com/103023/105022065-441f0a80-5a84-11eb-9dca-56fc3d6af8a9.png)

Or like `(ε | x y z)+` ([Oracle's style](https://docs.oracle.com/en/database/oracle/oracle-database/21/sqlrf/physical_attributes_clause.html#GUID-A15063A9-3237-43D3-B0AE-D01F6E80B393)):

![1-fs8](https://user-images.githubusercontent.com/103023/105023139-8f85e880-5a85-11eb-8f06-a807b90dba6b.png)

Or like `ε | (x y z)+` ([SQLite3's style](https://sqlite.org/syntax/join-clause.html)):


![1-fs8](https://user-images.githubusercontent.com/103023/105024266-da543000-5a86-11eb-926d-20b565f3712c.png)

In any case the rendered result will need 3 rows instead of 2 rows.

**Comment by dveeden** [comment]
Besides updating the things that predate this it might also be nice to add information into the `README.md` and/or `CONTRIBUTING.md` about how to work with the EBNF rendering and how to test it before submitting a PR.

**Comment by dveeden** [comment]
Current state:
```
$ git grep -c 'sqlgram/.*png'
functions-and-operators/set-operators.md:1
sql-statements/sql-statement-select.md:14
sql-statements/sql-statement-set-default-role.md:4
sql-statements/sql-statement-set-names.md:7
sql-statements/sql-statement-set-password.md:1
sql-statements/sql-statement-set-role.md:3
sql-statements/sql-statement-set-variable.md:2
sql-statements/sql-statement-show-bindings.md:4
sql-statements/sql-statement-show-builtins.md:1
sql-statements/sql-statement-show-character-set.md:2
sql-statements/sql-statement-show-collation.md:1
sql-statements/sql-statement-show-columns-from.md:10
sql-statements/sql-statement-show-config.md:2
sql-statements/sql-statement-show-create-sequence.md:2
sql-statements/sql-statement-show-create-table.md:2
sql-statements/sql-statement-show-create-user.md:2
sql-statements/sql-statement-show-databases.md:2
sql-statements/sql-statement-show-engines.md:1
sql-statements/sql-statement-show-errors.md:1
sql-statements/sql-statement-show-grants.md:5
sql-statements/sql-statement-show-histograms.md:3
sql-statements/sql-statement-show-indexes.md:5
sql-statements/sql-statement-show-plugins.md:2
sql-statements/sql-statement-show-privileges.md:1
sql-statements/sql-statement-show-processlist.md:2
sql-statements/sql-statement-show-profiles.md:1
sql-statements/sql-statement-show-stats-healthy.md:3
sql-statements/sql-statement-show-stats-meta.md:3
sql-statements/sql-statement-show-status.md:3
sql-statements/sql-statement-show-table-next-rowid.md:2
sql-statements/sql-statement-show-table-regions.md:5
sql-statements/sql-statement-show-table-status.md:3
sql-statements/sql-statement-show-tables.md:4
sql-statements/sql-statement-show-variables.md:3
sql-statements/sql-statement-show-warnings.md:1
sql-statements/sql-statement-shutdown.md:1
sql-statements/sql-statement-split-region.md:7
sql-statements/sql-statement-trace.md:2
sql-statements/sql-statement-truncate.md:3
sql-statements/sql-statement-update.md:6
sql-statements/sql-statement-use.md:2
statistics.md:3
```

**Comment by dveeden** [comment]
Maybe @terry1purcell can help with the `statistics.md` related sqlgrams/EBNF

**Comment by dveeden** [comment]
Current state:

```
$ git grep -c 'sqlgram/.*png'
functions-and-operators/set-operators.md:1
sql-statements/sql-statement-select.md:13
statistics.md:3
```

**Comment by dveeden** [comment]
Everything done. Thanks to everyone involved in this!
